import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Airdopes 141",
    price: 1299,
    oldPrice: 4490,
    features: ["ASAP™ Charge", "Clear Calling"],
    categoryName: "wirelessEarbuds",
  },
  {
    _id: uuid(),
    title: "Airdopes 131",
    price: 999,
    oldPrice: 2990,
    features: ["13mm Drivers", "IWP Technology"],
    categoryName: "wirelessEarbuds",
  },
  {
    _id: uuid(),
    title: "Airdopes 161",
    price: 999,
    oldPrice: 2490,
    features: ["ASAP™ Charge", "IWP Technology"],
    categoryName: "wirelessEarbuds",
  },
  {
    _id: uuid(),
    title: "Airdopes 115",
    price: 999,
    oldPrice: 2990,
    features: ["BEAST™ Mode", "13mm Drivers"],
    categoryName: "wirelessEarbuds",
  },
  {
    _id: uuid(),
    title: "Airdopes Max",
    price: 1499,
    oldPrice: 5490,
    features: ["ASAP™ Charge", "BEAST™ Mode", "ENx™ Technology"],
    categoryName: "wirelessEarbuds",
  },
  {
    _id: uuid(),
    title: "Airdopes 131 PRO",
    price: 1099,
    oldPrice: 2990,
    features: ["BEAST™ Mode", "Clear Calling"],
    categoryName: "wirelessEarbuds",
  },
  {
    _id: uuid(),
    title: "Airdopes Atom 83",
    price: 999,
    oldPrice: 3490,
    features: ["ASAP™ Charge", "13mm drivers"],
    categoryName: "wirelessEarbuds",
  },
  {
    _id: uuid(),
    title: "Airdopes Alpha",
    price: 999,
    oldPrice: 3490,
    features: ["ASAP™ Charge", "ENx™ Technology"],
    categoryName: "wirelessEarbuds",
  },
  {
    _id: uuid(),
    title: "Airdopes Atom 81",
    price: 1099,
    oldPrice: 3490,
    features: ["ASAP Fast Charge", "ENx™ Technology"],
    categoryName: "wirelessEarbuds",
  },
  {
    _id: uuid(),
    title: "Airdopes 141 Neo",
    price: 1399,
    oldPrice: 3990,
    features: ["ASAP™ Charge", "BEAST™ Mode", "ENx™ Technology"],
    categoryName: "wirelessEarbuds",
  },
  {
    _id: uuid(),
    title: "Airdopes 100",
    price: 999,
    oldPrice: 3490,
    features: ["ASAP™ Charge", "Clear Calling"],
    categoryName: "wirelessEarbuds",
  },
  {
    _id: uuid(),
    title: "Rockerz 235 V2",
    price: 899,
    oldPrice: 2990,
    features: ["Fast Charging", "10mm Drivers"],
    categoryName: "neckband",
  },
  {
    _id: uuid(),
    title: "Rockerz 255 Pro+",
    price: 1499,
    oldPrice: 3990,
    features: ["boAt Signature Sound", "10mm Drivers"],
    categoryName: "neckband",
  },
  {
    _id: uuid(),
    title: "Rockerz 330",
    price: 1299,
    oldPrice: 2990,
    features: ["boAt Signature Sound", "Metallic Control Panel"],
    categoryName: "neckband",
  },
  {
    _id: uuid(),
    title: "Rockerz 333",
    price: 1599,
    oldPrice: 3990,
    features: ["ASAP Charge", "10mm Dynamic Drivers", "Bluetooth v5.0"],
    categoryName: "neckband",
  },
  {
    _id: uuid(),
    title: "Rockerz 103 Pro",
    price: 1099,
    oldPrice: 2490,
    features: ["boAt Signature Sound", "10mm Drivers"],
    categoryName: "neckband",
  },
  {
    _id: uuid(),
    title: "Rockerz 255",
    price: 1299,
    oldPrice: 2990,
    features: ["IPX5 Water Resistance", "10mm Drivers"],
    categoryName: "neckband",
  },
  {
    _id: uuid(),
    title: "Rockerz 255R",
    price: 1499,
    oldPrice: 3990,
    features: ["boAt Signature Sound", "10mm Drivers"],
    categoryName: "neckband",
  },
  {
    _id: uuid(),
    title: "Rockerz 335",
    price: 1399,
    oldPrice: 3990,
    features: ["boAt Signature Sound", "10mm Drivers"],
    categoryName: "neckband",
  },
  {
    _id: uuid(),
    title: "Rockerz 235 Pro",
    price: 999,
    oldPrice: 1990,
    features: ["Voice Assistant", "BEAST™ Mode", "ENx™ Technology"],
    categoryName: "neckband",
  },
  {
    _id: uuid(),
    title: "Rockerz 260",
    price: 1299,
    oldPrice: 2499,
    features: ["Fast Charging", "10mm Drivers", "ENx™Technology"],
    categoryName: "neckband",
  },
  {
    _id: uuid(),
    title: "Rockerz 255 Neo",
    price: 1299,
    oldPrice: 2990,
    features: ["BEAST™ Mode", "10mm Drivers", "ENx™Technology"],
    categoryName: "neckband",
  },
  {
    _id: uuid(),
    title: "Wave Call",
    price: 1799,
    oldPrice: 7990,
    features: ["HD Curved Display", "Save upto 10 contacts"],
    categoryName: "smartWatch",
  },
  {
    _id: uuid(),
    title: "Wave Fury",
    price: 1399,
    oldPrice: 6999,
    features: ["30 Days Battery Life", '1.83" HD Display'],
    categoryName: "smartWatch",
  },
  {
    _id: uuid(),
    title: "Lunar Connect Ace",
    price: 2499,
    oldPrice: 9499,
    features: ['1.43" AMOLED Display', "100+ Sports Modes"],
    categoryName: "smartWatch",
  },
  {
    _id: uuid(),
    title: "Wave Call 2",
    price: 1299,
    oldPrice: 9499,
    features: ['1.83" HD Display', "Crest OS+", "700+ Active Modes"],
    categoryName: "smartWatch",
  },
  {
    _id: uuid(),
    title: "Wave Flex Connect",
    price: 1499,
    oldPrice: 7990,
    features: ["HD Curved Display", "Save upto 10 contacts"],
    categoryName: "smartWatch",
  },
  {
    _id: uuid(),
    title: "Lunar Call Plus",
    price: 2999,
    oldPrice: 9999,
    features: ["ENx™ Technology", "100 Watch Faces"],
    categoryName: "smartWatch",
  },
  {
    _id: uuid(),
    title: "Wave Stride Voice",
    price: 1999,
    oldPrice: 6990,
    features: ["100+ Sports Modes", "100+ Watch Faces"],
    categoryName: "smartWatch",
  },
  {
    _id: uuid(),
    title: "Storm Call",
    price: 1799,
    oldPrice: 7990,
    features: ["2.5D Curved Display", "Save upto 10 contacts"],
    categoryName: "smartWatch",
  },
  {
    _id: uuid(),
    title: "Wave Leap Call",
    price: 1499,
    oldPrice: 6990,
    features: ["100+ Sports Modes", "100+ Watch Faces"],
    categoryName: "smartWatch",
  },
  {
    _id: uuid(),
    title: "Lunar Connect Pro",
    price: 4299,
    oldPrice: 10999,
    features: ["700+ Active Modes", "Bluetooth Calling", "ASAP™ Charge"],
    categoryName: "smartWatch",
  },
  {
    _id: uuid(),
    title: "Xtend Plus",
    price: 2299,
    oldPrice: 8999,
    features: ['1.78" AMOLED display', "700 nits brightness"],
    categoryName: "smartWatch",
  },
  {
    _id: uuid(),
    title: "Rockerz 450 Polo",
    price: 2290,
    oldPrice: 3999,
    features: ["40mm Drivers", "Bluetooth v4.2", "300mAh Battery"],
    categoryName: "headphones",
  },
  {
    _id: uuid(),
    title: "Rockerz 410",
    price: 1599,
    oldPrice: 2990,
    features: ["Work from Home Pro", "40mm Dynamic Drivers"],
    categoryName: "headphones",
  },
  {
    _id: uuid(),
    title: "Rockerz 440",
    price: 999,
    oldPrice: 2999,
    features: ["40mm Drivers", "Bluetooth v5.0", "Lightweight design"],
    categoryName: "headphones",
  },
  {
    _id: uuid(),
    title: "Rockerz 400",
    price: 999,
    oldPrice: 2999,
    features: ["40mm Drivers", "Voice Assistant", "300mAh Battery"],
    categoryName: "headphones",
  },
  {
    _id: uuid(),
    title: "Rockerz 518",
    price: 2290,
    oldPrice: 3999,
    features: ["40mm Drivers", "Bluetooth v4.2", "300mAh Battery"],
    categoryName: "headphones",
  },
  {
    _id: uuid(),
    title: "Rockerz 450 - Masaba Edition",
    price: 1999,
    oldPrice: 3990,
    features: ["8 Hours Playback", "300mAh Battery"],
    categoryName: "headphones",
  },
  {
    _id: uuid(),
    title: "Nirvana 751 ANC",
    price: 4599,
    oldPrice: 7990,
    features: ["40mm Drivers", "ASAP Charge", "ANC Technology"],
    categoryName: "headphones",
  },
  {
    _id: uuid(),
    title: "Rockerz 558 Sunburn Edition",
    price: 2099,
    oldPrice: 4999,
    features: ["50mm Drivers", "20 Hours Playback", "500mAh Battery"],
    categoryName: "headphones",
  },
  {
    _id: uuid(),
    title: "Rockerz 650 Sunburn Edition",
    price: 1999,
    oldPrice: 4999,
    features: ["40mm Drivers", "60 Hours Playback", "Dual EQ Modes"],
    categoryName: "headphones",
  },
  {
    _id: uuid(),
    title: "Rockerz 650 DC Edition",
    price: 1999,
    oldPrice: 3990,
    features: ["40mm Drivers", "ASAP™ Charge", "Dual EQ Modes"],
    categoryName: "headphones",
  },
  {
    _id: uuid(),
    title: "Rockerz 450R",
    price: 1599,
    oldPrice: 3990,
    features: ["40mm Drivers", "Bluetooth v4.2", "300mAh Battery"],
    categoryName: "headphones",
  },
  {
    _id: uuid(),
    title: "Stone 1200",
    price: 2999,
    oldPrice: 6990,
    features: ["14W Signature Sound", "IPX7 Water Resistance"],
    categoryName: "speakers",
  },
  {
    _id: uuid(),
    title: "Stone 650R",
    price: 1999,
    oldPrice: 4990,
    features: ["Travel & Party Booster", "IPX7 Water Resistance"],
    categoryName: "speakers",
  },
  {
    _id: uuid(),
    title: "Stone 1208",
    price: 4099,
    oldPrice: 6990,
    features: ["RGB LEDs", "Bluetooth v5.0","76mm Drivers"],
    categoryName: "speakers",
  },
  {
    _id: uuid(),
    title: "Stone 500",
    price: 1999,
    oldPrice: 2990,
    features: ["RGB LEDs", "TWS Technology","10W Powerful Sound"],
    categoryName: "speakers",
  },
  {
    _id: uuid(),
    title: "Stone 190",
    price: 999,
    oldPrice: 2990,
    features: ["52mm Dynamic Driver", "IPX7 Water Resistance"],
    categoryName: "speakers",
  },
  {
    _id: uuid(),
    title: "Stone 180",
    price: 899,
    oldPrice: 2490,
    features: ["Lightweight Design", "IPX7 Water Resistance"],
    categoryName: "speakers",
  },
  {
    _id: uuid(),
    title: "Rugby Plus FM",
    price: 2999,
    oldPrice: 4990,
    features: ["52mm Drivers", "Type C interface","2000 mAh battery"],
    categoryName: "speakers",
  },
  {
    _id: uuid(),
    title: "Partypal 53",
    price: 3799,
    oldPrice: 7990,
    features: ["Bluetooth v5.1", "RGB LEDs","4.5H Playback"],
    categoryName: "speakers",
  },
  {
    _id: uuid(),
    title: "Stone 1200F",
    price: 3999,
    oldPrice: 6990,
    features: ["Up to 09HRS Playback", "RGB LED Lights"],
    categoryName: "speakers",
  },
  {
    _id: uuid(),
    title: "Partypal 50",
    price: 3999,
    oldPrice: 7990,
    features: ["RGB LED Lights", "IPX5 Water Resistance"],
    categoryName: "speakers",
  },
  {
    _id: uuid(),
    title: "Stone 1010",
    price: 3099,
    oldPrice: 6990,
    features: ["14W Signature Sound", "Huge 3000 mAh Battery"],
    categoryName: "speakers",
  },
];
